parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
extends:
  - eslint-config-getkey
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - react
parser: '@typescript-eslint/parser'
settings:
  react:
    version: detect
rules:
  '@typescript-eslint/interface-name-prefix':
    - off
  '@typescript-eslint/ban-ts-comment':
    - off
