default:
  image: node:lts-alpine
  cache:
    paths:
    - node_modules/
    - .yarn-cache

variables:
  YARN_CACHE_FOLDER: .yarn-cache

stages:
  - build
  - deploy

validate:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn lint
    - yarn test

build_js:
  stage: build
  before_script:
    - yarn install --production=false # get the devDeps
  script:
    - yarn build:prod
  artifacts:
    paths:
      - dist/

s3_prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 sync dist/ s3://editor.bombhopper.io/ --exclude '*.html' --exclude 'sw.js' --cache-control max-age=2419200
    # the html is uploaded last to avoid race conditions where scripts are missing
    - aws s3 sync dist/ s3://editor.bombhopper.io/ --exclude '*' --include '*.html' --include 'sw.js' --cache-control max-age=0,must-revalidate,public
  only:
    - master
  environment:
    name: production
    url: https://editor.bombhopper.io
  cache: {} # disable the cache for this job
