default:
  image: node:latest
  cache:
    paths:
    - node_modules/
    - .yarn-cache

variables:
  YARN_CACHE_FOLDER: .yarn-cache

stages:
  - build
  - deploy

validate_lint:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn lint

build_js:
  stage: build
  before_script:
    - yarn install --production=false # get the devDeps
  script:
    - yarn build:prod
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - cp -r dist public
    - find public -type f -iregex '.*\.\(html\|js\|css\|svg\|webmanifest\|fnt\|txt\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
      - public
  only:
    - master
  cache: {} # disable the cache for this job
  image: debian:latest # leaner than the node image
